### PR TITLE
Breaking change to normalize stubRequest method

### PR DESCRIPTION
**Pull request by marbemac**
Looks like it was written incorrectly from the start. Its signature is different than stubOnce, because it does not accept a method argument. Further, the comment/documentation in code indicates that it SHOULD accept the method, even though the function does not.

Its also not very useful without being able to specify the method. So, this fixes that, but is a breaking change, hence the major version bump.

### CODE REVIEW

**Comment by Tobbe** [comment]
Thanks for the PR 👍 

There are too many things going on here though :) Could you please create a separate PR with just the stubRequest fix, and a version bump to 0.7.0?

**Comment by Tobbe** [comment]
If you could please also add some code to `stubRequest` to check the number of arguments, and based off of that call ` this.stubs.track` with or without the method. That way we don't have to break backwards compatability.

Keep some of the tests with just two arguments, and add 'GET' as the method to some of them, so we test both versions

**Comment by marbemac** [comment]
Shite - forgot additional commits would be added here - only meant to add the first one - will do!

And yeah I can do the argument thing you suggested.

**Comment by Tobbe** [comment]
I implemented this myself and released v0.7.0. Closing this now.

**Pull request closed without merging**
